package com.semanticbits.employee;
// Generated 14 May, 2013 6:32:14 PM by Hibernate Tools 3.2.1.GA



/**
 * Userroles generated by hbm2java
 */
public class Userroles  implements java.io.Serializable {


     private UserrolesId id;

    public Userroles() {
    }

    public Userroles(UserrolesId id) {
       this.id = id;
    }
   
    public UserrolesId getId() {
        return this.id;
    }
    
    public void setId(UserrolesId id) {
        this.id = id;
    }




}


